alias cat="bat"
alias rm="rip"
alias lg="lazygit"
alias ..="cd .."
alias ...="cd ../.."
alias ccd="chezmoi cd"
alias cp="cp -i"

alias sa="s -p amazon"
alias sy="s -p youtube"
alias sw="s -p wikipedia"
