alias cat="bat"
alias rm="rip"
alias lg="lazygit"
alias ..="cd .."
alias ...="cd ../.."
alias ccd="chezmoi cd"
alias cp="cp -i"

alias sy="s -p youtube"
alias sw="s -p wikipedia"
alias sg="s -p github"
alias shn="s -p hackernews"
alias c="chezmoi"
alias dexter="ssh dexter"
alias p="pueue"
alias b="bartib"
alias j="just"
alias gpt="s -p gpt4o"
alias bing "s -p bing"
alias pi="ssh pi"
alias claude="s -p claude"
alias open="xdg-open &> /dev/null"
