# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = "$custom.healthchecks $all"
# format = "[$path]($style)[$read_only]($read_only_style) "

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green) ' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
format = "via [🤖 $version](bold green) "

[dotnet]
disabled = false

# [direnv]
# disabled = false
# [username]
# show_always = true

[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[cpp]
disabled = true


[custom.healthchecks]
# command = "cat ~/.local/share/starship/healthchecks.module/status"
# command = "cat $HOME/.local/share/starship/healthchecks.module/status"
command = "cat /home/sanjay/.local/share/starship/healthchecks.module/status"
shell = ["bash", "--noprofile", "--norc"]
# shell = ["sh", "-c", "--"]
# shell = ["sh", "-c"]
# command = "cat"
# args = ["~/.local/share/starship/healthchecks.module/status"]
format = "[$output]($style) "
style = "bold red"
when = "test -s /home/sanjay/.local/share/starship/healthchecks.module/status"
